# Generated by Django 5.0.3 on 2024-03-22 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
            },
            bases=('users.customuser',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('university_supervisor', 'University Supervisor'), ('company', 'Company'), ('company_supervisor', 'Company Supervisor'), ('department', 'Department'), ('registration', 'Registration'), ('ADMIN', 'Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('computer_science', 'Computer Science')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.student')),
            ],
        ),
    ]
