# Generated by Django 5.0.3 on 2024-03-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_alter_customuser_account_type_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('UNIVERSITY_SUPERVISOR', 'University Supervisor'), ('company', 'Company'), ('company_supervisor', 'Company Supervisor'), ('department', 'Department'), ('registration', 'Registration'), ('ADMIN', 'Admin')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
