# Generated by Django 5.0.3 on 2024-03-24 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='img_bk',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('UNIVERSITY_SUPERVISOR', 'University Supervisor'), ('COMPANY', 'Company'), ('COMPANY_SUPERVISOR', 'Company Supervisor'), ('DEPARTMENT', 'Department'), ('REGISTRATION', 'Registration'), ('ADMIN', 'Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('comp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='files')),
                ('img_bk', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='files')),
                ('img_bk', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('computer_science', 'Computer Science')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='files')),
                ('img_bk', models.FileField(blank=True, null=True, upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='University_Supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
