# Generated by Django 5.0.3 on 2024-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_studentprofile_id_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='img_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
