# Generated by Django 5.0.3 on 2024-04-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='companysupervisorprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.company'),
        ),
        migrations.AlterField(
            model_name='companysupervisorprofile',
            name='company_supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.companysupervisor'),
        ),
    ]
