# Generated by Django 5.0.3 on 2024-03-26 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_studentprofile_img_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='companysupervisorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='universitysupervisorprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Company', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companysupervisorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Company_supervisor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universitysupervisorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='University_Supervisor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
