# Generated by Django 5.0.3 on 2024-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_companyprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysupervisorprofile',
            name='first_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysupervisorprofile',
            name='last_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universitysupervisorprofile',
            name='first_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universitysupervisorprofile',
            name='last_name',
            field=models.CharField(blank=True, choices=[('amman', 'Amman'), ('Irbid', 'irbid'), ('zarqa', 'Zarqa')], max_length=50, null=True),
        ),
    ]
