# Generated by Django 4.2.11 on 2024-04-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_companysupervisor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='report_details',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='files\\signatures'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='week_number',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
