# Generated by Django 4.2.11 on 2024-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_weeklyreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
