# Generated by Django 5.0.3 on 2024-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
