# Generated by Django 4.2.11 on 2024-04-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_weeklyreport_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='university_supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.universitysupervisor'),
            preserve_default=False,
        ),
    ]
