# Generated by Django 4.2.11 on 2024-04-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_weeklyreport_university_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='company_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companysupervisor'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='university_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.universitysupervisor'),
        ),
    ]
