# Generated by Django 5.0.3 on 2024-04-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_studentprofile_bio_alter_studentprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
