# Generated by Django 5.0.3 on 2024-04-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_studentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
    ]
