# Generated by Django 4.2.11 on 2024-04-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_weeklyreport_company_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='signature',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='companySupervisorSignature',
            field=models.FileField(blank=True, null=True, upload_to='files\\signatures'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='universitySupervisorSignature',
            field=models.FileField(blank=True, null=True, upload_to='files\\signatures'),
        ),
    ]
