# Generated by Django 4.2.11 on 2024-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_student_location_remove_student_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companysupervisor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='companysupervisor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='companysupervisor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='universitysupervisor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='universitysupervisor',
            name='phone',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysupervisorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysupervisorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysupervisorprofile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universitysupervisorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universitysupervisorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
