# Generated by Django 5.0.3 on 2024-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_company_location_remove_company_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysupervisorprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='companysupervisor',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
