# Generated by Django 5.0.3 on 2024-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_trainingapplication_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='table_data',
            field=models.JSONField(default=list),
        ),
    ]
