# Generated by Django 5.0.3 on 2024-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_weeklyreport_table_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreport',
            old_name='date',
            new_name='date_begin',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='date_end',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
