# Generated by Django 4.2.11 on 2024-05-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_date_weeklyreport_date_begin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitynotification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='universitynotification',
            name='training_application',
        ),
        migrations.DeleteModel(
            name='StudentNotification',
        ),
        migrations.DeleteModel(
            name='UniversityNotification',
        ),
    ]
